### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by aneeshlingala** [siddpuri/coderogue#1]

**Comment by aneeshlingala** [comment]
You may know Indu Lingala in your Computer Science Principles (CSP) class! I do have some prior experience with [Code.org](https://code.org), and here is my
[current project](https://studio.code.org/projects/applab/tleUzJLotgXcmPCEKU34K1sQ35VjAw3lbqh3MiHlAHg). This project simulates a terminal (bash, cmd) on the site. I am her younger brother and I found his great piece of code. FYI, I am eleven years old (4 years younger). I really like Linux and I hope you too. Whats your favorite distribution? Mine is [Devuan](https://devuan.org). I would really like to know yours too! 

Have a great day,
Aneesh Lingala ([aneeshlingala.github.io](https://aneeshlingala.github.io))

**Comment by siddpuri** [comment]
Hi Aneesh,

I just saw your comment today! What a fun app! Looks like you'll be more than prepared for CS in high school.

My current favorite distribution is Arch, but on my AWS servers I run Amazon-Linux. I do keep getting confused by the differences.

Mr Puri
